// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXHTZbZzURRAFdz7lAU8xXo3e8Qt2VLH4',
    appId: '1:256843493349:web:7cbb3c574174d09e70490c',
    messagingSenderId: '256843493349',
    projectId: 'vexflutter',
    authDomain: 'vexflutter.firebaseapp.com',
    storageBucket: 'vexflutter.firebasestorage.app',
    measurementId: 'G-N9DEL6G3GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9wVmr2K0BGG_GKa0KyR5RUXhJoH4KPUo',
    appId: '1:256843493349:android:ca5b338c26be973470490c',
    messagingSenderId: '256843493349',
    projectId: 'vexflutter',
    storageBucket: 'vexflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc-MrHACk3MFqYxZMoR-Zl429bvbQAwEw',
    appId: '1:256843493349:ios:7812d7aeefdade2470490c',
    messagingSenderId: '256843493349',
    projectId: 'vexflutter',
    storageBucket: 'vexflutter.firebasestorage.app',
    iosBundleId: 'com.example.vexTasaLibre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc-MrHACk3MFqYxZMoR-Zl429bvbQAwEw',
    appId: '1:256843493349:ios:7812d7aeefdade2470490c',
    messagingSenderId: '256843493349',
    projectId: 'vexflutter',
    storageBucket: 'vexflutter.firebasestorage.app',
    iosBundleId: 'com.example.vexTasaLibre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXHTZbZzURRAFdz7lAU8xXo3e8Qt2VLH4',
    appId: '1:256843493349:web:d971df63d33ed74670490c',
    messagingSenderId: '256843493349',
    projectId: 'vexflutter',
    authDomain: 'vexflutter.firebaseapp.com',
    storageBucket: 'vexflutter.firebasestorage.app',
    measurementId: 'G-KMY1K6VXFG',
  );
}
